#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "slant"
    statusline_inactive_separator = "bar"
    buffer_index_type = 1
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    # self
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    default_indent = 4
    filetree_direction = "left"
    relativenumber = false

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "cycle"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = 'checkers'

[[layers]]
    name = 'chinese'

[[layers]]
    name = 'edit'

[[layers]]
    name = 'default'

[[layers]]
    name = 'format'

[[layers]]
    name = 'debug'

[[layers]]
    name = 'colorscheme'

[[layers]]
    name = 'tools'

[[layers]]
    name = 'denite'

[[custom_plugins]]
    name = 'wakatime/vim-wakatime'
    merged = 0

# 标准模式自动切换英文
[[custom_plugins]]
    name = 'ybian/smartim'
    merged = 0

[[custom_plugins]]
    name = 'aklt/plantuml-syntax'
    merged = 0
